### PR TITLE
Use cli-menu 4.0

### PR DESCRIPTION
**Pull request by edgrosvenor**
In reference to https://github.com/nunomaduro/laravel-console-menu/issues/23

I'm feeling pretty good about this. Everything I've used from the API works exactly as expected. I'll let you know if I run into anything odd going forward, but this should do the trick.

### CODE REVIEW

**Review by nunomaduro — APPROVED** [review]
This seems look to me, @owenvoke we may need to a major version on this. What do you think?

**Comment by owenvoke** [comment]
I think that a major version bump would probably be best. 👍

**Comment by nunomaduro** [comment]
Thanks @edgrosvenor!

@owenvoke can you test laravel zero 7 with this latest `dev-master`, and if is good give me the green flag?

**Comment by owenvoke** [comment]
I will test this when I'm back on Monday. :+1:

**Comment by nunomaduro** [comment]
You are the best!

**Comment by owenvoke** [comment]
We'll need to update the docs here to remove the references to methods that were removed.

Currently in the [README](https://github.com/nunomaduro/laravel-console-menu/blob/master/README.md#appearance), we mention that `setUnselectedMarker()` and `setSelectedMarker()` can be used. However, they have been removed and now cause a `Call to undefined method NunoMaduro\LaravelConsoleMenu\Menu::set*Marker()` error.

Other than that, this seems to work fine in Laravel Zero v7. :+1:

**Comment by nunomaduro** [comment]
@owenvoke Great! Fell free to update the readme, tag a new version, and tweet about it.

**Comment by owenvoke** [comment]
@nunomaduro, looks like I don't actually have access to tag it, so I'll leave this one to you if that's ok. 👍

**Comment by nunomaduro** [comment]
@owenvoke Check now : https://github.com/nunomaduro/laravel-console-menu/invitations

**Comment by simonovich** [comment]
> We'll need to update the docs here to remove the references to methods that were removed.
> 
> Currently in the [README](https://github.com/nunomaduro/laravel-console-menu/blob/master/README.md#appearance), we mention that `setUnselectedMarker()` and `setSelectedMarker()` can be used. However, they have been removed and now cause a `Call to undefined method NunoMaduro\LaravelConsoleMenu\Menu::set*Marker()` error.
> 

Okay, so now how do I change the marker?

**Comment by owenvoke** [comment]
@simonovich, you'll need to use `modifySelectableStyle()` as per the underlying package's docs. 👍🏻

https://github.com/php-school/cli-menu/blob/master/README.md#item-markers

**Comment by simonovich** [comment]
@owenvoke, Unfortunately this doesn't work as expected.
```php
    public function handle()
    {
        $option = (new NunoMaduro\LaravelConsoleMenu\Menu('Pizza menu'))
            ->modifySelectableStyle(function (SelectableStyle $style) {
                $style->setUnselectedMarker('❅ ')
                    ->setSelectedMarker('✏ ')

                    // disable unselected marker
                    ->setUnselectedMarker('');
            })
            ->addOption('mozzarella', 'Mozzarella')
            ->addOption('chicken_parm', 'Chicken Parm')
            ->addOption('sausage', 'Sausage')
            ->addQuestion('Make your own', 'Describe your pizza...')
            ->addOption('burger', 'Prefer burgers')
            ->setWidth(80)
            ->open();

        echo "You have chosen the option number #$option";
    }
```

See screenshot:
</img>

Menu items added via addOption() remained unchanged.

**Pull request merged**
